version: '3.3'

services:
  #
  #  Application
  #
  frontend:
    container_name: front
    image: lexlutter/wcharge-frontend:0.0.6
    ports:
      - "3000:3000"

  postgres:
    container_name: postgres
    image: postgres
    #    volumes:
    #      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'postgres'
  #    ports:
  #      - "5432:5432"

  wecharge-mqtt:
    container_name: wecharge-mqtt
    image: lexlutter/wcharge-mqtt:0.1.2-2
    environment:
      DISABLE_SWAGGER_HTTP_HANDLER: 'true'
      GRPC_PORT: 9090
      APP_NAME: wcharge_mqtt
      APP_VERSION: 0.0.1
      LOG_LEVEL: debug
      MQTT_URL: 'mqtt://guest:guest@rabbitmq:1883'
      RABBIT_URL: 'amqp://guest:guest@rabbitmq:5672/'
      GRAYLOG_URL: 'graylog:12201'
    ports:
      - "9090:9090"
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    ports:
      - "1883:1883"
      - "8883:8883"
      - "5672:5672"
    #      - "15672:15675"
    command: "/bin/bash -c \"rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt rabbitmq_amqp1_0; rabbitmq-server\""

  app:
    container_name: wecharge-backend
    image: lexlutter/wcharge-backend:0.1.2-3
    environment:
      PG_URL: 'postgres://user:pass@postgres:5432/postgres'
      #      GRPC_URL: 'amqp://guest:guest@rabbitmq:5672/'
      GRPC_URL: 'wecharge-mqtt:9090'
      RABBIT_URL: 'amqp://guest:guest@rabbitmq:5672/'
      RABBIT_CLIENT_ID: 10002
      PG_POOL_MAX: 8
      DISABLE_SWAGGER_HTTP_HANDLER: 'true'
      SESSION_HTTP_KEY: session_http_key
      APP_NAME: wcharge_back
      APP_VERSION: 1.1.1
      HTTP_PORT: 8080
      LOG_LEVEL: 'debug'
      GRAYLOG_URL: 'graylog:12201'
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  #
  #  Graylog
  #
  mongodb:
    image: "mongo:6.0.14"

  opensearch:
    image: "opensearchproject/opensearch:2.12.0"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=true"
      - "plugins.security.ssl.http.enabled=true"
      - "plugins.security.disabled=true"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=+_8r#wliY3Pv5-HMIf4qzXImYzZf"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: "on-failure"

  graylog:
    image: "graylog/graylog:6.0"
    depends_on:
      - mongodb
      - opensearch
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_PASSWORD_SECRET=5bde908bd4dee15dfb167a9c873fc4bb8a
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
    ports:
      - "12201:12201/udp"
      - "1514:1514/udp"
      - "5555:5555/udp"
      - "8531:9000/tcp"

#volumes:
#  pg-data:
