app:
  name: 'wcharge_back'
  version: '1.0.0'

http:
  port: '8080'
  session_http_key: 'session_http_key'

logger:
  log_level: 'debug'
  rollbar_env: 'wcharge_back'

postgres:
  URL: 'postgres://user:pass@localhost:5432/postgres'
  pool_max: 8


#rabbitmq:
#  rpc_server_exchange: 'rpc_server'
#  rpc_client_exchange: 'rpc_client'
