app:
  name: 'wcharge_back'
  version: '1.0.0'

http:
  port: '8888'
  session_http_key: 'session_http_key'

logger:
  log_level: 'debug'
  rollbar_env: 'wcharge_back'

postgres:
  url: 'postgres://postgres:postgres@localhost:5432/wch'
  pool_max: 8

grpc:
  url: "localhost:9999"

rabbit:
  url: 'amqp://guest:guest@89.111.154.223:5672/'
  client_id: '10002'

graylog:
  url: 'localhost:12201'