definitions:
  entity.Address:
    properties:
      address:
        type: string
      city:
        type: string
      country:
        type: string
      id:
        type: integer
      lat:
        type: number
      lng:
        type: number
    type: object
  entity.Powerbank:
    properties:
      capacity:
        description: объем заряда
        type: number
      create_at:
        type: string
      delete_at:
        type: string
      id:
        type: integer
      position:
        type: integer
      removed:
        type: boolean
      serial_number:
        type: string
      update_at:
        type: string
      used:
        description: сколько уже использована банка в часах // up юзается или нет
        type: boolean
    type: object
  entity.Role:
    properties:
      id:
        type: integer
      name:
        type: string
      privileges:
        type: integer
    type: object
  entity.Station:
    properties:
      address:
        type: integer
      address_full:
        $ref: '#/definitions/entity.Address'
      capacity:
        type: number
      create_at:
        type: string
      delete_at:
        type: string
      free_capacity:
        type: number
      id:
        type: integer
      powerbanks:
        items:
          $ref: '#/definitions/entity.Powerbank'
        type: array
      removed:
        type: boolean
      serial_number:
        type: string
      update_at:
        type: string
    type: object
  entity.User:
    properties:
      address:
        type: integer
      address_full:
        $ref: '#/definitions/entity.Address'
      create_at:
        type: string
      delete_at:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      password_hash:
        type: string
      password_salt:
        type: string
      phone:
        type: string
      removed:
        type: boolean
      role:
        type: integer
      role_full:
        $ref: '#/definitions/entity.Role'
      update_at:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /addresses:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Address'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get info about all addresses
    post:
      parameters:
      - description: Country
        in: body
        name: Country
        required: true
        schema:
          type: string
      - description: City
        in: body
        name: City
        required: true
        schema:
          type: string
      - description: Address
        in: body
        name: Address
        required: true
        schema:
          type: string
      - description: Latitude
        in: body
        name: Lat
        required: true
        schema:
          type: number
      - description: Longitude
        in: body
        name: Lng
        required: true
        schema:
          type: number
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Address'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create address
  /addresses/{addressId}:
    delete:
      parameters:
      - description: Address Id
        in: path
        name: addressId
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete address
    get:
      parameters:
      - description: Address Id
        in: path
        name: addressId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Address'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get info about address
    put:
      parameters:
      - description: Address Id
        in: path
        name: addressId
        required: true
        type: integer
      - description: Country
        in: body
        name: Country
        required: true
        schema:
          type: string
      - description: City
        in: body
        name: City
        required: true
        schema:
          type: string
      - description: Address
        in: body
        name: Address
        required: true
        schema:
          type: string
      - description: Latitude
        in: body
        name: Lat
        required: true
        schema:
          type: number
      - description: Longitude
        in: body
        name: Lng
        required: true
        schema:
          type: number
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Address'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update address
  /powerbanks:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Powerbank'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get info about all powerbanks
    post:
      parameters:
      - description: Serial number of powerbank
        in: body
        name: SerialNumber
        required: true
        schema:
          type: string
      - description: Full capacity on powerbank
        in: body
        name: Capacity
        required: true
        schema:
          type: number
      - description: Status on use's powerbanks
        in: body
        name: Used
        required: true
        schema:
          type: boolean
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Powerbank'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create powerbank
  /powerbanks/{powerbankId}:
    delete:
      parameters:
      - description: Powerbank Id
        in: path
        name: powerbankId
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create powerbank
    get:
      parameters:
      - description: Powerbank Id
        in: path
        name: powerbankId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Powerbank'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get info about powerbank
    put:
      parameters:
      - description: Powerbank Id
        in: path
        name: powerbankId
        required: true
        type: integer
      - description: Status on use's powerbanks
        in: body
        name: Used
        required: true
        schema:
          type: boolean
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Powerbank'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create powerbank
  /stations:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Station'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get info about all stations
    post:
      parameters:
      - description: Serial number of station
        in: body
        name: SerialNumber
        required: true
        schema:
          type: string
      - description: Address Id
        in: body
        name: Address
        required: true
        schema:
          type: integer
      - description: Full capacity on station
        in: body
        name: Capacity
        required: true
        schema:
          type: number
      - description: Free capacity on station
        in: body
        name: FreeCapacity
        required: true
        schema:
          type: number
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Station'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create station
  /stations/{stationId}:
    delete:
      parameters:
      - description: Station Id
        in: path
        name: stationId
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete station
    get:
      parameters:
      - description: Station Id
        in: path
        name: stationId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Station'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get info about station
    put:
      parameters:
      - description: Station Id
        in: path
        name: stationId
        required: true
        type: integer
      - description: Address Id
        in: body
        name: Address
        required: true
        schema:
          type: integer
      - description: Free capacity on station
        in: body
        name: FreeCapacity
        required: true
        schema:
          type: number
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Station'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update station
  /stations/{stationId}/powerbanks:
    get:
      parameters:
      - description: Station Id
        in: path
        name: stationId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Powerbank'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get powerbanks in station
    post:
      parameters:
      - description: Station Id
        in: path
        name: stationId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Take random powerbank from station
  /stations/{stationId}/powerbanks/{powerbankId}:
    post:
      parameters:
      - description: Station Id
        in: path
        name: stationId
        required: true
        type: integer
      - description: Powerbank Id
        in: path
        name: powerbankId
        required: true
        type: integer
      - description: Powerbank's position in station
        in: body
        name: Position
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add powerbank to station
    put:
      parameters:
      - description: Station Id
        in: path
        name: stationId
        required: true
        type: integer
      - description: Powerbank Id
        in: path
        name: powerbankId
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Return powerbank to station
  /users:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get info about all users
    post:
      parameters:
      - description: Username
        in: body
        name: UserName
        required: true
        schema:
          type: string
      - description: Email
        in: body
        name: Email
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: Password
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create station
  /users/{userId}:
    delete:
      parameters:
      - description: User Id
        in: path
        name: userId
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete station
    get:
      parameters:
      - description: User Id
        in: path
        name: userId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get info about user
    put:
      parameters:
      - description: User Id
        in: path
        name: userId
        required: true
        type: integer
      - description: Username
        in: body
        name: UserName
        required: true
        schema:
          type: string
      - description: Email
        in: body
        name: Email
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: Password
        required: true
        schema:
          type: string
      - description: Address Id
        in: body
        name: Address
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update station
  /users/{userId}/powerbanks:
    get:
      parameters:
      - description: User Id
        in: path
        name: userId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Powerbank'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get info about all powerbanks of users
swagger: "2.0"
